<a href="https://colab.research.google.com/github/Denis2488/DL/blob/master/%22IdentifyingSpecialMatrices%22.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Identifying special matrices
## Instructions
В этом задании вы напишите функцию, которая будет проверять перед вычислением матрицы  4×4, не будет ли она сингулярной, то есть, существует ли к ней инверсия.

Используйте метод преобразования матрицы к эшелонированной по строкам форме и проверки, если это не удастся, оставив нули, которые нельзя удалить на главной диагонали.
Не беспокойтесь, если вы раньше не программировали, фреймворк для функции уже написан.
В коде отмечены места, где надо внести изменения.
Первые две строки уже написаны, можно использовать их как подсказку, чтобы сделать последние две.

### Матрицы в Python
В пакете *numpy* в Python индексация матриц начинается с нуля для самого верхнего столбца и самой левой строки.
Т.е. матричная структура выглядит так:

```python
A[0, 0]  A[0, 1]  A[0, 2]  A[0, 3]
A[1, 0]  A[1, 1]  A[1, 2]  A[1, 3]
A[2, 0]  A[2, 1]  A[2, 2]  A[2, 3]
A[3, 0]  A[3, 1]  A[3, 2]  A[3, 3]
```
Вы можете получить доступ к значению каждого элемента в отдельности, используя
```python
A[n, m]
```
который даст n-ую строку и m-й столбец (начиная с нуля).

Вы также можете получить доступ ко всей строке одновременно, используя
```python
A[n]
```
как вы увидите, это будет полезно при расчете линейных комбинаций строк.

Последнее примечание - Python чувствителен к отступам.
Весь код, который надо написать, должен быть на том же уровне отступа, что и комментарий с инструкциями.

Пожалуйста, не меняйте имена функций.
Удачи!

In [ ]:
# GRADED FUNCTION
import numpy as np

# Наша функция будет проходить через матрицу, изменяя каждую строку так, чтобы привести матрицу к эшелонированной форме.
# Если в какой-то момент она не сможет поставить 1 в главную диагональ,
# мы вернем значение True, в противном случае мы вернем False.
# Эту функцию изменять не надо.


def isSingular(A) :
    B = np.array(A, dtype=np.float_) #  Делает B как копию матрицы A, так как мы будем менять ее значения.
    try:
        fixRowZero(B)
        fixRowOne(B)
        fixRowTwo(B)
        fixRowThree(B)
    except MatrixIsSingular:
        return True
    return False

# Следующая строка определяет наш флаг ошибки, когда что-то идет не так, и это значит матрица сингулярная.
# Нет необходимости редактировать эту строку.
class MatrixIsSingular(Exception): pass
# Для Row Zero все, что нам нужно, это первый элемент, равный 1.
# Мы разделим строку на значение A [0, 0].
# Однако, если A [0, 0] равно 0, это доставит нам неприятности, поэтому сначала мы ее проверим на ноль,
# и если это так,  перед делением мы прибавим одну из нижних строк к первой.
# Будем повторять проверку для каждого ряда снизу, пока деление не станет возможным. Если так и не найдем нужную строку, значит, матрица сингулярна
# Нет необходимости редактировать эту функцию.

def fixRowZero(A) :
    if A[0,0] == 0 :
        A[0] = A[0] + A[1]
    if A[0,0] == 0 :
        A[0] = A[0] + A[2]
    if A[0,0] == 0 :
        A[0] = A[0] + A[3]
    if A[0,0] == 0 :
        raise MatrixIsSingular()
    A[0] = A[0] / A[0,0]
    return A

# Сначала мы установим элементы под главной диагональю в ноль, то есть A [1,0].
# Далее нам надо, чтобы элемент на диагонали был равен единице, и мы разделим строку на значение A [1, 1].
# Опять же, нам нужно проверить, не ноль ли это.
# Если это так, мы прибавим нижнюю строку и повторим установку поддиагональных элементов в ноль.
# Нет необходимости редактировать эту функцию.
def fixRowOne(A) :
    A[1] = A[1] - A[1,0] * A[0]
    if A[1,1] == 0 :
        A[1] = A[1] + A[2]
        A[1] = A[1] - A[1,0] * A[0]
    if A[1,1] == 0 :
        A[1] = A[1] + A[3]
        A[1] = A[1] - A[1,0] * A[0]
    if A[1,1] == 0 :
        raise MatrixIsSingular()
    A[1] = A[1] / A[1,1]
    return A

# Это первая функция, которую вы должны выполнить.
# Следуйте инструкциям внутри функции при каждом комментарии
def fixRowTwo(A) :
    # Вставьте код ниже, чтобы установить поддиагональные элементы второй строки в ноль (их два).
    A[2] = A[2] - A[2, 0] * A[0]
    A[2] = A[2] - A[2, 1] * A[1]
    # Далее мы проверим, что диагональный элемент не равен нулю.
    if A[2,2] == 0 :
        # Вставьте код ниже, который добавляет нижнюю строку в строку 2.
        A[2] = A[2] + A[3]
        A[2] = A[2] - A[2, 0] * A[0]
        # Теперь повторите ваш код, который устанавливает поддиагональные элементы на ноль.
        A[2] = A[2] - A[2, 1] * A[1]        
    if A[2,2] == 0 :
        raise MatrixIsSingular()
    # Наконец, установите диагональный элемент в единицу, разделив всю строку на этот элемент.
    A[2] = A[2] / A[2, 2]
    return A

# Вы также должны сами выполнить эту функцию
# Следуйте инструкциям внутри функции.
def fixRowThree(A) :
    # Вставьте код ниже, чтобы установить субдиагональные элементы строки три в ноль.
    A[3] = A[3] - A[3, 0] * A[0]
    A[3] = A[3] - A[3, 1] * A[1]
    A[3] = A[3] - A[3, 2] * A[2]
    # Завершите оператор if, чтобы проверить, равен ли диагональный элемент нулю.
    if A[3, 3] == 0:
        raise MatrixIsSingular()
    # Преобразуйте строку, чтобы установить диагональный элемент в единицу.
    A[3] = A[3] / A[3, 3]
    return A

## Проверьте свой код перед отправкой
Чтобы проверить код, который вы написали выше, запустите ячейку (выберите ячейку выше, затем нажмите кнопку воспроизведения [▶ |] или нажмите Shift-Enter).
Затем вы можете использовать приведенный ниже код для проверки вашей функции.
Эта ячейка не оценивается; можете изменять и запускать ее сколько угодно.

Попробуйте свой код на сложных тестовых случаях!


In [ ]:
V = np.array([[1,0,2,6],
              [0,1,8,2],
              [2,8,3,1],
              [1,-6,2,3]], dtype=np.float_)
gsBasis4(V)

NameError: ignored

In [ ]:
# Once you've done Gram-Schmidt once,
# doing it again should give you the same result. Test this:
U = gsBasis4(V)
gsBasis4(U)

NameError: ignored

In [ ]:
# Try the general function too.
gsBasis(V)

array([[ 0.40824829, -0.1814885 ,  0.04982278,  0.89325973],
       [ 0.        ,  0.1088931 ,  0.99349591, -0.03328918],
       [ 0.81649658,  0.50816781, -0.06462163, -0.26631346],
       [ 0.40824829, -0.83484711,  0.07942048, -0.36063281]])

In [ ]:
# See what happens for non-square matrices
A = np.array([[3,2,3],
              [2,5,-1],
              [2,4,8],
              [12,2,1]], dtype=np.float_)
gsBasis(A)

array([[ 0.23643312,  0.18771349,  0.22132104],
       [ 0.15762208,  0.74769023, -0.64395812],
       [ 0.15762208,  0.57790444,  0.72904263],
       [ 0.94573249, -0.26786082, -0.06951101]])

In [ ]:
dimensions(A)

NameError: ignored

In [ ]:
B = np.array([[6,2,1,7,5],
              [2,8,5,-4,1],
              [1,-6,3,2,8]], dtype=np.float_)
gsBasis(B)

array([[ 0.93704257, -0.12700832, -0.32530002,  0.        ,  0.        ],
       [ 0.31234752,  0.72140727,  0.61807005,  0.        ,  0.        ],
       [ 0.15617376, -0.6807646 ,  0.71566005,  0.        ,  0.        ]])

In [ ]:
dimensions(B)

3.0

In [ ]:
# Now let's see what happens when we have one vector that is a linear combination of the others.
C = np.array([[1,0,2],
              [0,1,-3],
              [1,0,2]], dtype=np.float_)
gsBasis(C)

array([[0.70710678, 0.        , 0.        ],
       [0.        , 1.        , 0.        ],
       [0.70710678, 0.        , 0.        ]])

In [ ]:
dimensions(C)

2.0